# Generated by Django 5.0.7 on 2024-07-22 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_chats_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorites',
            name='remind_me',
            field=models.CharField(blank=True, choices=[('Two times before deadline', 'Two times before deadline'), ('Three times before deadline', 'Three times before deadline')], max_length=50, null=True, verbose_name='Reminder options'),
        ),
        migrations.AddField(
            model_name='favorites',
            name='track',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.DeleteModel(
            name='TrackScholarships',
        ),
    ]
