# Generated by Django 5.0.7 on 2024-07-22 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_favorites_remind_me_favorites_track_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorites',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
