# Generated by Django 5.0.7 on 2024-07-23 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_feedback_updated_at_user_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='custom_instruction',
            field=models.TextField(blank=True, max_length=250, null=True, verbose_name='Custom Instruction'),
        ),
    ]
