# Generated by Django 5.0.7 on 2024-07-26 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_chats_output_remove_threads_metadata_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chats',
            name='content',
            field=models.TextField(max_length=500, verbose_name='Content'),
        ),
    ]
