# Generated by Django 5.0.7 on 2024-07-26 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_chats_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chats',
            old_name='created_at',
            new_name='createdAt',
        ),
        migrations.RenameField(
            model_name='chats',
            old_name='thread_id',
            new_name='threadId',
        ),
        migrations.RenameField(
            model_name='favorites',
            old_name='created_at',
            new_name='createdAt',
        ),
        migrations.RenameField(
            model_name='favorites',
            old_name='updated_at',
            new_name='updatedAt',
        ),
        migrations.RenameField(
            model_name='favorites',
            old_name='user_id',
            new_name='userId',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='chat_id',
            new_name='chatId',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='created_at',
            new_name='createdAt',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='updated_at',
            new_name='updatedAt',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='user_id',
            new_name='userId',
        ),
        migrations.RenameField(
            model_name='threads',
            old_name='created_at',
            new_name='createdAt',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='updated_at',
            new_name='updatedAt',
        ),
    ]
