# Generated by Django 5.0.7 on 2024-08-08 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_chats_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='chats',
            name='searchType',
            field=models.CharField(choices=[('DatabaseSearch', 'DatabaseSearch'), ('GoogleSearch', 'GoogleSearch')], default='DatabaseSearch', max_length=50, verbose_name='SearchType'),
        ),
    ]
