# Generated by Django 5.0.7 on 2024-08-12 17:51

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_chats_searchtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scholarships',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('description', models.TextField(max_length=150, verbose_name='Description')),
                ('eligibility', models.TextField(blank=True, max_length=150, null=True, verbose_name='Eligbility')),
                ('value', models.CharField(blank=True, max_length=100, null=True, verbose_name='Value')),
                ('fields', models.CharField(blank=True, max_length=100, null=True, verbose_name='Fields')),
                ('deadline', models.CharField(max_length=100, verbose_name='Deadline')),
                ('hostCountry', models.CharField(max_length=100, verbose_name='Host Country')),
                ('website', models.CharField(max_length=100, verbose_name='Website')),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
