# Generated by Django 5.0.7 on 2024-08-12 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_scholarships'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholarships',
            name='deadline',
            field=models.DateTimeField(verbose_name='Deadline'),
        ),
    ]
