# Generated by Django 5.0.7 on 2024-08-14 00:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_ratelimit'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratelimit',
            name='createdAt',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
