# Generated by Django 5.0.7 on 2024-08-14 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_ratelimit_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ratelimit',
            old_name='window_start',
            new_name='last_request',
        ),
    ]
